caskdata/tephra

- tephra-core/src/main/java/co/cask/tephra/util/TxUtils.java
- tephra-hbase-compat-0.94/src/test/java/co/cask/tephra/hbase94/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
Modifies the time range end used for reads to include the current transaction's write pointer and adds testing around write visibility.
> TEPHRA-65 Transaction in progress should be able to read its own writes

- tephra-core/pom.xml
- tephra-core/src/main/java/co/cask/tephra/TransactionServiceMain.java
- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-core/src/main/java/co/cask/tephra/coprocessor/TransactionStateCache.java
- tephra-core/src/main/java/co/cask/tephra/distributed/TransactionServiceClient.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionStateStorage.java
- tephra-core/src/main/java/co/cask/tephra/runtime/ZKModule.java
- tephra-core/src/main/java/co/cask/tephra/util/ConfigurationFactory.java
- tephra-core/src/main/java/co/cask/tephra/util/ConfigurationProvider.java
- tephra-core/src/main/java/co/cask/tephra/util/HBaseVersion.java
- tephra-core/src/main/java/co/cask/tephra/util/HBaseVersionSpecificFactory.java
- tephra-core/src/test/java/co/cask/tephra/TransactionContextTest.java
- tephra-core/src/test/java/co/cask/tephra/TransactionExecutorTest.java
- tephra-core/src/test/java/co/cask/tephra/TransactionManagerTest.java
- tephra-core/src/test/java/co/cask/tephra/TransactionServiceMainTest.java
- tephra-core/src/test/java/co/cask/tephra/TransactionSystemTest.java
- tephra-core/src/test/java/co/cask/tephra/hbase/AbstractTransactionVisibilityFilterTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/HDFSTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/LocalTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/TransactionEditTest.java
- tephra-core/src/test/java/co/cask/tephra/util/AbstractConfigurationProviderTest.java
- tephra-hbase-compat-0.94/src/main/java/co/cask/tephra/hbase94/HBase94ConfigurationProvider.java
- tephra-hbase-compat-0.94/src/test/java/co/cask/tephra/hbase94/HBase94ConfigurationProviderTest.java
- tephra-hbase-compat-0.94/src/test/java/co/cask/tephra/hbase94/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/HBase96ConfigurationProvider.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/HBase96ConfigurationProviderTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/HBase98ConfigurationProvider.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/HBase98ConfigurationProviderTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilterTest.java
Removes all remaining usage of HBase classes in the tephra-core module.
> TEPHRA-5 remove use of HBaseConfiguration in tephra-core

- tephra-core/src/main/java/co/cask/tephra/AbstractTransactionAwareTable.java
- tephra-hbase-compat-0.94/src/main/java/co/cask/tephra/hbase94/TransactionAwareHTable.java
- tephra-hbase-compat-0.94/src/test/java/co/cask/tephra/hbase94/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/TransactionAwareHTable.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
This patch minimizes the change set retained in memory by TransactionAwareHTable, where possible.  For HBase 0.94, we still need to retain the full row + family + qualifier for all write in the change set.  However in HBase 0.96+, the delete API now supports a version-specific column family delete.  This allows us to retain just the row + family in the change set when using row-level conflict detection.  In the case of transaction rollback, we simply issue version specific deletes for each row + family that was written.  This minimizes the change set we must retain in memory and reduces the number of delete operations we must issue for rollback, potentially by a large amount.
> TEPHRA-82 Minimize change set retained by client for row-level conflict detection

- README.rst
- bin/tephra-env.sh
- conf/logback.xml
- pom.xml
- tephra-core/pom.xml
- tephra-core/src/main/java/co/cask/tephra/TransactionManager.java
- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-core/src/main/java/co/cask/tephra/coprocessor/TransactionStateCache.java
- tephra-core/src/main/java/co/cask/tephra/metrics/DefaultMetricsCollector.java
- tephra-core/src/main/java/co/cask/tephra/metrics/MetricsCollector.java
- tephra-core/src/main/java/co/cask/tephra/metrics/TxMetricsCollector.java
- tephra-core/src/main/java/co/cask/tephra/persist/AbstractTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionStateStorage.java
- tephra-core/src/main/java/co/cask/tephra/persist/LocalFileTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/LocalFileTransactionStateStorage.java
- tephra-core/src/main/java/co/cask/tephra/runtime/TransactionDistributedModule.java
- tephra-core/src/main/java/co/cask/tephra/runtime/TransactionInMemoryModule.java
- tephra-core/src/main/java/co/cask/tephra/runtime/TransactionLocalModule.java
- tephra-core/src/test/java/co/cask/tephra/persist/HDFSTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/LocalTransactionStateStorageTest.java
- tephra-hbase-compat-0.94/src/test/java/co/cask/tephra/hbase94/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessorTest.java
Currently Tephra only ships with a no-op stub for metrics collection.  This means that every user must implement their own MetricsCollector implementation, wire it in to the Guice injection, and compile and package Tephra in order to use it.
This change adds a built-in implementation based on Dropwizard Metrics, which supports JMX and file-based reporting out of the box.
> TEPHRA-73 Add a metrics collector implementation that does reporting via JMX and logging

- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/TransactionAwareHTable.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessorTest.java
This changes the HBase 0.96 and 0.98 TransactionAwareHTable implementations to pass Delete operations from the client when a delete is performed.  This will decouple client-side change set tracking from server-side implementation details of how delete markers are handled.
This is not supported in HBase 0.94, since the server-side row lock obtained outside the coprocessor hook in HBase 0.94 does not allow us to perform a Put operation on the same row as the Delete is being performed upon.
> TEPHRA-91 Clients should send normal Delete operations for deletes

- README.rst
- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/TransactionAwareHTable.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
When using row-level conflict detection, and performing a row or column family delete, TransactionAwareHTable will now issue a row or family delete operation.  Previously, TransactionAwareHTable would first read all the columns in the row or family, and issue individual column deletes on each one.  At the moment, row and family deletes can only be supported with row-level conflict detection, since with column-level conflict detection, the TransactionAwareHTable must first find which columns would be deleted in order to include them in the change set.
TransactionProcessor has been updated to know how to handle column family delete markers, and to inject the family delete marker column into all read operations.
> TEPHRA-70 Add support for row delete markers when using row-level conflict detection

- tephra-core/src/main/java/co/cask/tephra/distributed/TransactionService.java
I log an error if the hostname can't be resolved, but probably should consider throwing a runtime exception or something, as registering 0.0.0.0 is pretty much useless for a client to connect
> tephra-86 resolve hostname for address 0.0.0.0

- README.rst
- pom.xml
- tephra-core/src/main/java/co/cask/tephra/util/ConfigurationFactory.java
- tephra-core/src/main/java/co/cask/tephra/util/HBaseVersion.java
- tephra-core/src/main/java/co/cask/tephra/util/HBaseVersionSpecificFactory.java
- tephra-core/src/test/java/co/cask/tephra/util/HBaseVersionTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/pom.xml
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/Filters.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/HBase10ConfigurationProvider.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/SecondaryIndexTable.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/TransactionAwareHTable.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/HBase10ConfigurationProviderTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-1.0/pom.xml
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/Filters.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/HBase10ConfigurationProvider.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/SecondaryIndexTable.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/TransactionAwareHTable.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/HBase10ConfigurationProviderTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilterTest.java
This adds two new compatibility modules to support the two new versions of HBase:
* tephra-hbase-compat-1.0 - supports Apache HBase 1.0.x releases
* tephra-hbase-compat-1.0-cdh - supports the modified version of HBase shipped in CDH 5.4
Since the version of HBase shipped in CDH 5.4 is neither binary nor source compatible with Apache HBase 1.0, it needs to be supported as a separate build artifact.
> TEPHRA-53 Add HBase 1.0 compatibility

- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessorTest.java
This change ensures that we preserve the timestamp set on family delete markers in the TransactionProcessor coprocessor.  This is the right thing to do from the server standpoint and ensures we interoperate nicely with Phoenix secondary index handling.
> TEPHRA-104 Use cell timestamps when generating family delete markers

- tephra-core/src/main/java/co/cask/tephra/TransactionContext.java
- tephra-core/src/test/java/co/cask/tephra/TransactionContextTest.java
- Removal is only allowed if there is no active transaction
- This is the prevent the TransactionAware being left in some unknown state
> (TEPHRA-117) Added the TransactionContext.removeTransactionAware method

- tephra-core/src/main/java/co/cask/tephra/distributed/AbstractClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/ElasticPool.java
- tephra-core/src/main/java/co/cask/tephra/distributed/PooledClientProvider.java
- tephra-core/src/test/java/co/cask/tephra/distributed/PooledClientProviderTest.java
When more threads then the size of the client pool try to get a client in parallel this either results in a deadlock (just try to run the provided test without the fixes) or the `ElasticPool`'s internal queue overflows when one client too much is returned to the pool (with only the fix in the `AbstractClientProvider`).
Cause was that the pool was initialized twice. Once from within the pools `getClientPool()` method and once when creating the first client in the `newClient()` method. I solved this by creating a custom `initializePool()` method instead of overriding the original `initialize()` method.
> Fix deadlock in PooledClientProvider

- tephra-core/src/main/java/co/cask/tephra/persist/TransactionEdit.java
- tephra-core/src/main/java/co/cask/tephra/persist/TransactionEditCodecs.java
- tephra-core/src/test/java/co/cask/tephra/persist/LocalTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/TransactionEditTest.java
Cleans up the TransactionEditCodec handling, pulling the existing codecs out of TransactionEdit and into TransactionEditCodecs.  Also makes each codec be referenced once so that the version check is not duplicated.
> TEPHRA-119 Clean up TransactionEditCodec handling and fix V4

- pom.xml
- tephra-distribution/pom.xml
- tephra-examples/pom.xml
- tephra-examples/src/main/java/co/cask/tephra/examples/BalanceBooks.java
- tephra-examples/src/main/java/co/cask/tephra/examples/package-info.java
- tephra-examples/src/test/java/co/cask/tephra/examples/BalanceBooksTest.java
This change adds a new tephra-examples module, with a sample application to serve as a Tephra smoke test.
Currently the tephra-examples module is hardcoded to depend on tephra-hbase-compat-1.0-cdh.  This allows it to be easily integrated, but it would be better if users could compile the examples against whatever version of HBase they are using.  We could accomplish this as a future enhancement by:
* adding a TableFactory class which implements HBaseVersionSpecificFactory.  This would sit in tephra-core and be used by the examples to obtain the correct version of TransactionAwareHTable for the HBase version being used
* add Maven profiles to tephra-examples for each of the supported HBase versions.  The user could then compile the examples code against whatever version of HBase is being …
> TEPHRA-120 Add a simple smoke test to validate functionality on a cluster

- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-core/src/main/java/co/cask/tephra/util/TxUtils.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilterTest.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/coprocessor/TransactionVisibilityFilterTest.java
Approach: 
Any cell with timestamp lesser than a pre-determined time is assumed to be pre-existing data, i.e., data written before table was converted into transactional table using Tephra. TTL for such cells is calculated differently than transactional cells.
Also, time range filter while doing get and scan has been updated to allow cells with non-transactional time.
This leads to Tephra working with data that was written to any HBase tables before those tables were made transactional using Tephra.
Note: I have made changes only to tephra-hbase-compat-0.98 module. If the changes look good then I'll port them to the other compat modules too.
> TEPHRA-89 Allow pre-existing, non-transactional data in HBase tables

- tephra-api/src/main/java/co/cask/tephra/Transaction.java
- tephra-core/src/main/java/co/cask/tephra/distributed/TransactionConverterUtils.java
- tephra-core/src/main/java/co/cask/tephra/distributed/thrift/TVisibilityLevel.java
- tephra-core/src/main/thrift/transaction.thrift
- tephra-core/src/test/java/co/cask/tephra/TransactionTest.java
- tephra-core/src/test/java/co/cask/tephra/distributed/ThriftTransactionServerTest.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/TransactionAwareHTableTest.java
JIRA - https://issues.cask.co/browse/TEPHRA-134
Add a new transaction visibility level to return all snapshots visible to current transaction
Note: I've made changes only to HBase-0.98 compat modules, I'll port the changes over to other modules after the review.
> TEPHRA-134 Add a new transaction visibility level SNAPSHOT_ALL

- README.rst
- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-core/src/main/java/co/cask/tephra/distributed/AbstractClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/CloseableThriftClient.java
- tephra-core/src/main/java/co/cask/tephra/distributed/ElasticPool.java
- tephra-core/src/main/java/co/cask/tephra/distributed/PooledClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/RetryWithBackoff.java
- tephra-core/src/main/java/co/cask/tephra/distributed/SingleUseClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/ThreadLocalClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/ThriftClientProvider.java
- tephra-core/src/main/java/co/cask/tephra/distributed/TransactionServiceClient.java
- tephra-core/src/main/java/co/cask/tephra/distributed/TransactionServiceThriftClient.java
- tephra-core/src/test/java/co/cask/tephra/distributed/PooledClientProviderTest.java
Simplify ElasticPool implementation.
Also introduced a timeout (default of 3 seconds), so the `obtain()` method call isn't indefinite.
https://issues.cask.co/browse/CDAP-4067
https://issues.cask.co/browse/TEPHRA-142
> TEPHRA-142 improve elastic pool

- tephra-core/src/main/java/co/cask/tephra/distributed/ElasticPool.java
- tephra-core/src/test/java/co/cask/tephra/distributed/ElasticPoolTest.java
Move ElasticPoolTest from CDAP Project
Changes also needed to be made to it:
recycle method of the ElasticPool subclass needs to determine whether to discard the element or not.
To do this, added a validity field on the Dummy class.
> Move ElasticPoolTest from CDAP Project

- tephra-core/src/main/java/co/cask/tephra/AbstractTransactionAwareTable.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/TransactionAwareHTable.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/TransactionAwareHTable.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/TransactionAwareHTable.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/TransactionAwareHTable.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/TransactionAwareHTableTest.java
JIRA : https://issues.cask.co/browse/TEPHRA-131
Fix : Include the column family byte[] to the change set
Once the initial review is complete, the fix (including unit test) will be ported to other compact modules. 
Thanks to @JamesRTaylor for filing the JIRA and for also providing the patch.
> TEPHRA-131 Fix rollback of family delete when ConflictDetection.ROW is used

- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/TransactionAwareHTable.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/TransactionAwareHTableTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/TransactionAwareHTable.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/TransactionAwareHTable.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/TransactionAwareHTable.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/TransactionAwareHTableTest.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/TransactionAwareHTable.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/TransactionAwareHTableTest.java
@poornachandra  @JamesRTaylor
Tephra preserves attributes for Puts, but not Deletes. I modified TransactionAwareHTable.transactionalizeAction(Delete delete) and TransactionProcessor.preDelete() to preserve the Delete attributes.
> TEPHRA-135 Delete should preserve attributes

- tephra-core/src/main/java/co/cask/tephra/TxConstants.java
- tephra-core/src/main/java/co/cask/tephra/persist/AbstractTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/CommitMarkerCodec.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionLogReaderSupplier.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionLogReaderV1.java
- tephra-core/src/main/java/co/cask/tephra/persist/HDFSTransactionLogReaderV2.java
- tephra-core/src/main/java/co/cask/tephra/persist/LocalFileTransactionLog.java
- tephra-core/src/main/java/co/cask/tephra/persist/TransactionLogWriter.java
- tephra-core/src/test/java/co/cask/tephra/persist/AbstractTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/CommitMarkerCodecTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/HDFSTransactionLogTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/HDFSTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/persist/LocalTransactionStateStorageTest.java
- tephra-core/src/test/java/co/cask/tephra/util/TransactionEditUtil.java
1) we persist the count of transaction log-edits we are appending before performing the append.
2) with this information, while reading the transaction log for replay, we know  the count of edits to read and if we reach EOF before reading those entries, we will safely ignore the entries we have read so far.
3) we use a buffer to add the transaction edit entries and serve from that buffer. we repeat step-2 after the buffer is emptied.
for backward compatibility, we have a version metadata written to sequence file and we use the new-logic only if the version metadata is present in the sequence file. 
files which was written with previous version of code and if they were closed abruptly and hit EOF, we would still face the issue described in TEPHRA-133.
> TEPHRA-133 - handle transation edit log improper close

- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/CellSkipFilter.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionFilters.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.96/src/main/java/co/cask/tephra/hbase96/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/CellSkipFilterTest.java
- tephra-hbase-compat-0.96/src/test/java/co/cask/tephra/hbase96/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/CellSkipFilter.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionFilters.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-0.98/src/main/java/co/cask/tephra/hbase98/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/CellSkipFilterTest.java
- tephra-hbase-compat-0.98/src/test/java/co/cask/tephra/hbase98/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/CellSkipFilter.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionFilters.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0-cdh/src/main/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/CellSkipFilterTest.java
- tephra-hbase-compat-1.0-cdh/src/test/java/co/cask/tephra/hbase10cdh/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/CellSkipFilter.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionFilters.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.0/src/main/java/co/cask/tephra/hbase10/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/CellSkipFilterTest.java
- tephra-hbase-compat-1.0/src/test/java/co/cask/tephra/hbase10/coprocessor/TransactionProcessorTest.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/CellSkipFilter.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionFilters.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionProcessor.java
- tephra-hbase-compat-1.1/src/main/java/co/cask/tephra/hbase11/coprocessor/TransactionVisibilityFilter.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/coprocessor/CellSkipFilterTest.java
- tephra-hbase-compat-1.1/src/test/java/co/cask/tephra/hbase11/coprocessor/TransactionProcessorTest.java
JIRA: https://issues.cask.co/browse/TEPHRA-169
Added filter `TransactionCellSkipFilter` that delegates to the `TransactionVisibilityFilter` for all the filter operations. However it also remembers the last `Cell` for which `TransactionVisibilityFilter` returned the `NEXT_COL` code, so that when the filter receives the same cell with different version again, it returns `NEXT_COL` without consulting the `TransactionVisibilityFilter`.
> TEPHRA-169 Added filter to skip the cells with different timestamps.
